<?php
require_once 'tests/HTTP/TaintedArray.php';

require_once 'PHPUnit/Framework/TestCase.php';

/**
 * TaintedArray test case.
 */
class TaintedArrayTest extends PHPUnit_Framework_TestCase
{

    /**
     *
     * @var TaintedArray
     */
    private $TaintedArray;

    /**
     * Prepares the environment before running a test.
     */
    protected function setUp()
    {
        parent::setUp();
        
        // TODO Auto-generated TaintedArrayTest::setUp()
        
        $this->TaintedArray = new TaintedArray(/* parameters */);
    }

    /**
     * Cleans up the environment after running a test.
     */
    protected function tearDown()
    {
        // TODO Auto-generated TaintedArrayTest::tearDown()
        $this->TaintedArray = null;
        
        parent::tearDown();
    }

    /**
     * Constructs the test case.
     */
    public function __construct()
    {
        // TODO Auto-generated constructor
    }

    /**
     * Tests TaintedArray->__construct()
     */
    public function test__construct()
    {
        // TODO Auto-generated TaintedArrayTest->test__construct()
        $this->markTestIncomplete("__construct test not implemented");
        
        $this->TaintedArray->__construct(/* parameters */);
    }

    /**
     * Tests TaintedArray->__toString()
     */
    public function test__toString()
    {
        // TODO Auto-generated TaintedArrayTest->test__toString()
        $this->markTestIncomplete("__toString test not implemented");
        
        $this->TaintedArray->__toString(/* parameters */);
    }

    /**
     * Tests TaintedArray->useStrict()
     */
    public function testUseStrict()
    {
        // TODO Auto-generated TaintedArrayTest->testUseStrict()
        $this->markTestIncomplete("useStrict test not implemented");
        
        $this->TaintedArray->useStrict(/* parameters */);
    }

    /**
     * Tests TaintedArray->sanitizeWithCheck()
     */
    public function testSanitizeWithCheck()
    {
        // TODO Auto-generated TaintedArrayTest->testSanitizeWithCheck()
        $this->markTestIncomplete("sanitizeWithCheck test not implemented");
        
        $this->TaintedArray->sanitizeWithCheck(/* parameters */);
    }

    /**
     * Tests TaintedArray->sanitizeAsObjectProperty()
     */
    public function testSanitizeAsObjectProperty()
    {
        // TODO Auto-generated TaintedArrayTest->testSanitizeAsObjectProperty()
        $this->markTestIncomplete("sanitizeAsObjectProperty test not implemented");
        
        $this->TaintedArray->sanitizeAsObjectProperty(/* parameters */);
    }

    /**
     * Tests TaintedArray->setDefault()
     */
    public function testSetDefault()
    {
        // TODO Auto-generated TaintedArrayTest->testSetDefault()
        $this->markTestIncomplete("setDefault test not implemented");
        
        $this->TaintedArray->setDefault(/* parameters */);
    }

    /**
     * Tests TaintedArray->markAsAutogenerated()
     */
    public function testMarkAsAutogenerated()
    {
        // TODO Auto-generated TaintedArrayTest->testMarkAsAutogenerated()
        $this->markTestIncomplete("markAsAutogenerated test not implemented");
        
        $this->TaintedArray->markAsAutogenerated(/* parameters */);
    }

    /**
     * Tests TaintedArray->isAutogenerated()
     */
    public function testIsAutogenerated()
    {
        // TODO Auto-generated TaintedArrayTest->testIsAutogenerated()
        $this->markTestIncomplete("isAutogenerated test not implemented");
        
        $this->TaintedArray->isAutogenerated(/* parameters */);
    }

    /**
     * Tests TaintedArray->length()
     */
    public function testLength()
    {
        // TODO Auto-generated TaintedArrayTest->testLength()
        $this->markTestIncomplete("length test not implemented");
        
        $this->TaintedArray->length(/* parameters */);
    }

    /**
     * Tests TaintedArray->getDefaultData()
     */
    public function testGetDefaultData()
    {
        // TODO Auto-generated TaintedArrayTest->testGetDefaultData()
        $this->markTestIncomplete("getDefaultData test not implemented");
        
        $this->TaintedArray->getDefaultData(/* parameters */);
    }
}

